// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLZjLQGwvjOAU3oIe5AaoalUH1FVuDp8',
    appId: '1:308756769683:web:e9bb9ce8d9fd0f9cc19666',
    messagingSenderId: '308756769683',
    projectId: 'petdot-fc57e',
    authDomain: 'petdot-fc57e.firebaseapp.com',
    storageBucket: 'petdot-fc57e.appspot.com',
    measurementId: 'G-0TC40GG2MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZNEqsvCeJNPL2Cmj4024DFdzK22cZTMI',
    appId: '1:308756769683:android:fec5e80804b8cf9ec19666',
    messagingSenderId: '308756769683',
    projectId: 'petdot-fc57e',
    storageBucket: 'petdot-fc57e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49b73Pk8ILDSnB7b6GmcPCOjywWhFrUI',
    appId: '1:308756769683:ios:8662a4565ea203f5c19666',
    messagingSenderId: '308756769683',
    projectId: 'petdot-fc57e',
    storageBucket: 'petdot-fc57e.appspot.com',
    iosClientId: '308756769683-odidsarf7173j7c4v6n2ic3fbeienj30.apps.googleusercontent.com',
    iosBundleId: 'com.example.petdot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49b73Pk8ILDSnB7b6GmcPCOjywWhFrUI',
    appId: '1:308756769683:ios:6fbdb87071a3d852c19666',
    messagingSenderId: '308756769683',
    projectId: 'petdot-fc57e',
    storageBucket: 'petdot-fc57e.appspot.com',
    iosClientId: '308756769683-pce7qpvphe0d178h6fu8logda8t6anlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.petdot.RunnerTests',
  );
}
